### PR TITLE
Add support for OCaml 4.14

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The non-prefixed C API has been deprecated in 4.14 for removal in 5.0

**Comment by kit-ty-kate** [comment]
Hi, could we have a release with this fix?

**Comment by toolslive** [comment]
You want me to create a tag ?

**Comment by kit-ty-kate** [comment]
yes, and publish it to opam-repository if possible

**Comment by toolslive** [comment]
ok, I published a release here. Adapted the ordma.opam to opam's current whims.
Tried to publish via `opam publish`, This clones `git@github.com:ocaml/opam-repository.git` 
and tries to commit new file  `ordma/ordma.0.0.6/opam ordma.0.0.6` which fails with:
```
[ERROR] Uncaught exception: "/usr/bin/git commit -m Package ordma.0.0.6" exited with code 128
```
now what ?!

**Comment by kit-ty-kate** [comment]
This points to an issue with your locally installed git, i'm not sure. If you want to debug this you can go to your `~/.opam/plugins/opam-publish/repos/ocaml%opam-repository` directory and re-try the same command:
```
git commit -m "Package ordma.0.0.6"
```
and see what it says.

But just in case you don't have time to do it i've called opam-publish locally and it worked for me so i opened the PR:
https://github.com/ocaml/opam-repository/pull/30260

**Comment by toolslive** [comment]
ah....
```
git commit -m "Package ordma.0.0.6"
Author identity unknown
```
yes, I don't have a global git config. I guess the `opam-publish` assumes too much about people's setup.

Anyway,
I guess there's nothing left for me to do, so I can curl back up in torpor.

**Pull request merged**
